# Generated by Django 4.0.2 on 2022-05-04 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Subtitulo')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion')),
                ('ordering', models.FloatField(default=0, verbose_name='Orden')),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'ordering': ['-ordering', 'created'],
            },
        ),
    ]
